{
 "title": "PowerMax",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "serial",
    "label": "Serial",
    "query": {
     "query": "label_values({job=\"powermax\"},serial)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Write response time",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "powermax_Array_WriteResponseTime{serial=~\"$serial\"}"
    }
   ]
  },
  {
   "title": "Read response time",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "powermax_Array_ReadResponseTime{serial=~\"$serial\"}"
    }
   ]
  },
  {
   "title": "Read %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "powermax_Array_PercentReads{serial=~\"$serial\"}"
    }
   ]
  },
  {
   "title": "Write %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "powermax_Array_PercentWrites{serial=~\"$serial\"}"
    }
   ]
  },
  {
   "title": "Data Reduction Ratio (to 1)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "powermax_Array_DataReductionRatioOnReducible{serial=~\"$serial\"}"
    }
   ]
  },
  {
   "title": "Total Host IO",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "powermax_Array_HostIOs{serial=~\"$serial\"}"
    }
   ]
  },
  {
   "title": "Total Host MB",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "powermax_Array_HostMBs{serial=~\"$serial\"}"
    }
   ]
  },
  {
   "title": "Cache Hit %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "powermax_Array_PercentHit{serial=~\"$serial\"}"
    }
   ]
  },
  {
   "title": "FrontEnd Dir Util",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(powermax_FEDirector_PercentBusy{serial=~\"$serial\"})"
    }
   ]
  },
  {
   "title": "Total FE Req",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(powermax_FEDirector_HostIOs{serial=~\"$serial\"})"
    }
   ]
  },
  {
   "title": "BackEnd Dir Util",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(powermax_BEDirector_PercentBusy{serial=~\"$serial\"})"
    }
   ]
  },
  {
   "title": "Total BE Req",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "powermax_Array_BEIOs{serial=~\"$serial\"}"
    }
   ]
  },
  {
   "title": "RDF Dir Util",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(powermax_RDFDirector_PercentBusy{serial=~\"$serial\"})"
    }
   ]
  },
  {
   "title": "Total RDF IO",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(powermax_RDFDirector_IOs{serial=~\"$serial\"})"
    }
   ]
  },
  {
   "title": "Used Capacity TB",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(powermax_DiskGroup_UsedCapacity{serial=~\"$serial\"} / 1024)"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "powermax_Array_DiskUtilization{serial=~\"$serial\"}"
    }
   ]
  },
  {
   "title": "FrontEnd Director IO",
   "type": "timeseries",
   "description": "IO per second",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "powermax_FEDirector_HostIOs{serial=~\"$serial\"}",
     "legendFormat": "{{FEDirector}}"
    }
   ]
  },
  {
   "title": "FrontEnd Director Troughput",
   "type": "timeseries",
   "description": "Bytes/sec",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "powermax_FEDirector_HostMBs{serial=~\"$serial\"}",
     "legendFormat": "{{FEDirector}}"
    }
   ]
  },
  {
   "title": "Backend Director IO",
   "type": "timeseries",
   "description": "IO per second",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "powermax_BEDirector_IOs{serial=~\"$serial\"}",
     "legendFormat": "{{BEDirector}}"
    }
   ]
  },
  {
   "title": "FrontEnd Ports IO",
   "type": "timeseries",
   "description": "IO per second",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "powermax_FEPort_IOs{serial=~\"$serial\"}",
     "legendFormat": "{{FEPort}}"
    }
   ]
  },
  {
   "title": "Storagegroup write response times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "powermax_StorageGroup_WriteResponseTime{serial=~\"$serial\"}",
     "legendFormat": "{{StorageGroup}}"
    }
   ]
  },
  {
   "title": "Storagegroup write IO",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "powermax_StorageGroup_HostWrites{serial=~\"$serial\"}",
     "legendFormat": "{{StorageGroup}}"
    }
   ]
  },
  {
   "title": "Storagegroup read response times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "powermax_StorageGroup_ReadResponseTime{serial=~\"$serial\"}",
     "legendFormat": "{{StorageGroup}}"
    }
   ]
  },
  {
   "title": "Storagegroup read IO",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "powermax_StorageGroup_HostReads{serial=~\"$serial\"}",
     "legendFormat": "{{StorageGroup}}"
    }
   ]
  },
  {
   "title": "FrontEnd read response",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "powermax_FEDirector_ReadResponseTime{serial=~\"$serial\"}",
     "legendFormat": "{{FEDirector}}"
    }
   ]
  },
  {
   "title": "FrontEnd write response",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "powermax_FEDirector_WriteResponseTime{serial=~\"$serial\"}",
     "legendFormat": "{{FEDirector}}"
    }
   ]
  },
  {
   "title": "Tech Pool Used TB",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "powermax_DiskTechPool_UsedCapacity{serial=~\"$serial\"}",
     "legendFormat": "{{DiskTechPool}}"
    }
   ]
  },
  {
   "title": "FrontEnd Ports %Busy",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "powermax_FEPort_PercentBusy{serial=~\"$serial\"}",
     "legendFormat": "{{FEPort}}"
    }
   ]
  },
  {
   "title": "Array Capacity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum(powermax_DiskGroup_UsedCapacity{serial=~\"$serial\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(powermax_DiskGroup_TotalCapacity{serial=~\"$serial\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Board MBs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "powermax_Board_InboundMBs{serial=~\"$serial\"}",
     "legendFormat": "Inbound B{{Board}}"
    },
    {
     "expr": "powermax_Board_OutboundMBs{serial=~\"$serial\"}",
     "legendFormat": "Outbound B{{Board}}"
    }
   ]
  },
  {
   "title": "DiskGroup Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "powermax_DiskGroup_UsedCapacity{serial=~\"$serial\"}",
     "legendFormat": "Used {{DiskGroup}}"
    },
    {
     "expr": "powermax_DiskGroup_TotalCapacity{serial=~\"$serial\"}",
     "legendFormat": "Total {{DiskGroup}}"
    }
   ]
  },
  {
   "title": "IO Density",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "powermax_DiskGroup_IODensity{serial=~\"$serial\"}",
     "legendFormat": "DiskGroup {{DiskGroup}}"
    },
    {
     "expr": "powermax_DiskTechPool_IODensity{serial=~\"$serial\"}",
     "legendFormat": "TechPool {{DiskTechPool}}"
    }
   ]
  },
  {
   "title": "StorageGroup Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "powermax_StorageGroup_CapacityGB{serial=~\"$serial\"}",
     "legendFormat": "{{StorageGroup}}"
    }
   ]
  },
  {
   "title": "StorageGroup Effective Used Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "powermax_StorageGroup_EffectiveUsedCapacityGB{serial=~\"$serial\"}",
     "legendFormat": "{{StorageGroup}}"
    }
   ]
  },
  {
   "title": "StorageGroup Unreducible Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "powermax_StorageGroup_UnreducibleDataGB{serial=~\"$serial\"}",
     "legendFormat": "{{StorageGroup}}"
    }
   ]
  },
  {
   "title": "StorageGroup Data Reduction Ratio (to one)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": ":1" } },
   "targets": [
    {
     "expr": "powermax_StorageGroup_DataReductionRatio{serial=~\"$serial\"}",
     "legendFormat": "{{StorageGroup}}"
    }
   ]
  }
 ]
}